#pragma once

#define CMD_I2C_WRITE 0x91
#define CMD_I2C_READ 0x92
#define CMD_SET_I2C_MODE 0x94
#define CMD_SET_I2C_TIMEOUT 0x97
#define CMD_CLEAR_BUS 0x98
#define CMD_I2C_WRITE_AND_READ 0x9B
#define CMD_SET_STM32_TIMING 0xA1
#define CMD_DIGITAL_READ 0xA2
#define CMD_ENABLE_VCC_OUT 0xA4
#define CMD_GET_DEVICE_INFO 0xA7
#define CMD_GET_DEBUG_DATA 0xDC

#define ERROR_NONE 0
#define ERROR_PROTOCOL 1
#define ERROR_PREVIOUS_TIMEOUT 2
#define ERROR_TIMEOUT 3
#define ERROR_ADDRESS_TIMEOUT 4
#define ERROR_TX_TIMEOUT 5
#define ERROR_RX_TIMEOUT 6
#define ERROR_NACK 7
#define ERROR_ADDRESS_NACK 8
#define ERROR_TX_DATA_NACK 9
#define ERROR_BUS_ERROR 10
#define ERROR_ARBITRATION_LOST 11
#define ERROR_OTHER 12
#define ERROR_NOT_SUPPORTED 13

#define I2C_STANDARD_MODE 0
#define I2C_FAST_MODE 1
#define I2C_FAST_MODE_PLUS 2
#define I2C_10_KHZ 3
